[package]
name = "stodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
ptree = "0.4.0"
regex = "1.5.5"
petgraph = "0.6.0"
crossterm = "0.23"